# Generated by Django 5.1.7 on 2025-03-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('comum', 'Comum'), ('lojista', 'Lojista')], default='comum', max_length=10, verbose_name='Tipo de usuário'),
        ),
    ]
